package gestor_pokemon;

import es.discoduroderoer.ficheros.Texto;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class EnlazaMovimientos extends javax.swing.JDialog {

    private String[] datosFormaAprendizaje;

    public EnlazaMovimientos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setDefaultButton(this.btnGuardarNuevo);
        this.datosFormaAprendizaje = new String[3];
        rellenarCmb();
        this.setLocationRelativeTo(null);
        
    }

    private void rellenarCmb() {

        String sql = "select numero_pokedex, nombre from pokemon order by numero_pokedex";

        VariablesGlobales.conexion.rellenaComboBox2Columnas(this.cmbPokemon,
                sql,
                "--Seleccione un pokemon--",
                "numero_pokedex",
                "nombre");

        sql = "select id_movimiento, nombre from movimiento order by nombre";

        VariablesGlobales.conexion.rellenaComboBox2Columnas(this.cmbMovimiento,
                sql,
                "--Seleccione un movimiento--",
                "id_movimiento",
                "nombre");

        sql = "select id_tipo_aprendizaje, tipo_aprendizaje from tipo_forma_aprendizaje";

        VariablesGlobales.conexion.rellenaComboBox2Columnas(this.cmbTipoAprendizaje,
                sql,
                "",
                "id_tipo_aprendizaje",
                "tipo_aprendizaje");

    }

    private void rellenaFormaAprendizaje() {
        String[] filaCombobox = (String[]) (this.cmbTipoAprendizaje.getSelectedItem());
        int codigoTipoAprendizaje = Integer.parseInt(filaCombobox[0]);

        if (codigoTipoAprendizaje != -1) {

            String table = "";
            String columna = "";

            switch (codigoTipoAprendizaje) {
                case 1:
                    table = "mt";
                    columna = "mt";

                    btnAniadirTipo.setText("Añadir MT...");
                    break;
                case 2:
                    table = "mo";
                    columna = "mt";
                    btnAniadirTipo.setText("Añadir MO...");
                    break;
                case 3:
                    table = "nivel_aprendizaje";
                    columna = "nivel";
                    btnAniadirTipo.setText("Añadir nivel...");
                    break;
            }

            datosFormaAprendizaje[0] = table;
            datosFormaAprendizaje[1] = columna;
            datosFormaAprendizaje[2] = codigoTipoAprendizaje+"";
            

            String sql = "select id_forma_aprendizaje, " + columna + " "
                    + "from " + table + " order by " + columna;

            VariablesGlobales.conexion.rellenaComboBox2Columnas(this.cmbFormaAprendizaje,
                    sql,
                    "--Seleccione una forma aprendizaje--",
                    "id_forma_aprendizaje",
                    columna);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPokemon = new javax.swing.JComboBox<>();
        cmbMovimiento = new javax.swing.JComboBox<>();
        cmbTipoAprendizaje = new javax.swing.JComboBox<>();
        btnGuardarNuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFiltroPokemon = new javax.swing.JTextField();
        txtFiltroMov = new javax.swing.JTextField();
        cmbFormaAprendizaje = new javax.swing.JComboBox<>();
        btnAniadirTipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbTipoAprendizaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoAprendizajeItemStateChanged(evt);
            }
        });

        btnGuardarNuevo.setText("Guardar y nuevo");
        btnGuardarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNuevoActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pokemon");

        jLabel2.setText("Movimiento");

        jLabel3.setText("Forma");

        txtFiltroPokemon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroPokemonKeyReleased(evt);
            }
        });

        txtFiltroMov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroMovKeyReleased(evt);
            }
        });

        btnAniadirTipo.setText("Añadir ...");
        btnAniadirTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoAprendizaje, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cmbFormaAprendizaje, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAniadirTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnGuardarNuevo)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton2))
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbMovimiento, javax.swing.GroupLayout.Alignment.LEADING, 0, 204, Short.MAX_VALUE)
                                        .addComponent(cmbPokemon, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFiltroPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFiltroMov, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltroPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltroMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipoAprendizaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFormaAprendizaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAniadirTipo))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarNuevo)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNuevoActionPerformed

        String[] filaCombobox = (String[]) (this.cmbPokemon.getSelectedItem());
        int codigoPokemon = Integer.parseInt(filaCombobox[0]);

        filaCombobox = (String[]) (this.cmbMovimiento.getSelectedItem());
        int codigoMovimiento = Integer.parseInt(filaCombobox[0]);

        filaCombobox = (String[]) (this.cmbTipoAprendizaje.getSelectedItem());
        int codigoTipoApredizaje = Integer.parseInt(filaCombobox[0]);

        filaCombobox = (String[]) (this.cmbFormaAprendizaje.getSelectedItem());
        int codigoFormaApredizaje = Integer.parseInt(filaCombobox[0]);

        String errores = "";

        if (codigoPokemon == -1) {
            errores += " - Debes seleccionar un pokemon\n";
        }

        if (codigoMovimiento == -1) {
            errores += " - Debes seleccionar un movimiento\n";
        }

        if (codigoTipoApredizaje == -1) {
            errores += " - Debes seleccionar un tipo de aprendizaje\n";
        }

        if (codigoFormaApredizaje == -1) {
            errores += " - Debes seleccionar un pokemon\n";
        }

        if (errores.equals("")) {

            try {
                String sql = "insert into pokemon_movimiento_forma values(" + codigoPokemon + ", " + codigoMovimiento + ", " + codigoFormaApredizaje + ");";

                VariablesGlobales.conexion.ejecutarInstruccion(sql);

                Texto.escribirFicheroCaracteresBuf("enlazar_movimientos.txt", sql + "\r\n", true);

                JOptionPane.showMessageDialog(this, "Insertado correctamente", "Exito", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(this, errores, "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnGuardarNuevoActionPerformed

    private void txtFiltroMovKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroMovKeyReleased

        String sql = "select id_movimiento, nombre "
                + "from movimiento "
                + "where upper(nombre) like '%" + this.txtFiltroMov.getText().toUpperCase() + "%' "
                + "order by nombre";

        VariablesGlobales.conexion.rellenaComboBox2Columnas(this.cmbMovimiento,
                sql,
                "--Seleccione un movimiento--",
                "id_movimiento",
                "nombre");

    }//GEN-LAST:event_txtFiltroMovKeyReleased

    private void txtFiltroPokemonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroPokemonKeyReleased

        String sql = "select numero_pokedex, nombre "
                + "from pokemon "
                + "where upper(nombre) like '" + this.txtFiltroPokemon.getText().toUpperCase() + "%' "
                + "order by numero_pokedex";

        VariablesGlobales.conexion.rellenaComboBox2Columnas(this.cmbPokemon,
                sql,
                "--Seleccione un pokemon--",
                "numero_pokedex",
                "nombre");


    }//GEN-LAST:event_txtFiltroPokemonKeyReleased

    private void cmbTipoAprendizajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoAprendizajeItemStateChanged

        rellenaFormaAprendizaje();
    }//GEN-LAST:event_cmbTipoAprendizajeItemStateChanged

    private void btnAniadirTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirTipoActionPerformed

        AnidirFormaAprendizaje ventana = new AnidirFormaAprendizaje(this, true, datosFormaAprendizaje);
        ventana.setVisible(true);
        rellenaFormaAprendizaje();

    }//GEN-LAST:event_btnAniadirTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadirTipo;
    private javax.swing.JButton btnGuardarNuevo;
    private javax.swing.JComboBox<String> cmbFormaAprendizaje;
    private javax.swing.JComboBox<String> cmbMovimiento;
    private javax.swing.JComboBox<String> cmbPokemon;
    private javax.swing.JComboBox<String> cmbTipoAprendizaje;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFiltroMov;
    private javax.swing.JTextField txtFiltroPokemon;
    // End of variables declaration//GEN-END:variables
}
